"""empty message

Revision ID: 0c507bd10bd4
Revises: d0d8eeef382f
Create Date: 2020-10-20 15:29:03.169657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c507bd10bd4'
down_revision = 'd0d8eeef382f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_categories', sa.Column('name_uz', sa.String(length=100), nullable=True))
    op.add_column('dishes', sa.Column('description_uz', sa.String(length=1500), nullable=True))
    op.add_column('dishes', sa.Column('name_uz', sa.String(length=100), nullable=True))
    op.alter_column('dishes', 'description',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'description',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    op.drop_column('dishes', 'name_uz')
    op.drop_column('dishes', 'description_uz')
    op.drop_column('dish_categories', 'name_uz')
    # ### end Alembic commands ###
