"""empty message

Revision ID: d0d8eeef382f
Revises: 0484066c12fd
Create Date: 2020-10-20 15:24:47.901224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d8eeef382f'
down_revision = '0484066c12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_categories', sa.Column('name_uz', sa.String(length=100), nullable=True))
    op.add_column('dishes', sa.Column('description_uz', sa.String(length=500), nullable=True))
    op.add_column('dishes', sa.Column('name_uz', sa.String(length=100), nullable=True))
    op.alter_column('dishes', 'description',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dishes', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
    op.drop_column('dishes', 'name_uz')
    op.drop_column('dishes', 'description_uz')
    op.drop_column('dish_categories', 'name_uz')
    # ### end Alembic commands ###
